const $=(s,root=document)=>root.querySelector(s),$$=(s,root=document)=>[...root.querySelectorAll(s)];
const state={concept:'etalon',tab:'brand',capContent:'monogram',capFinish:'silver',capTechnique:'laser',sku:'medium'};
const SKUS={small:{volume:'0,3 л',ph:'pH 12'},medium:{volume:'0,5 л',ph:'pH 8.0'},large:{volume:'1 л',ph:'pH 8.0'}};
const ASSETS=window.EMBEDDED_ASSETS||{};
const asset=p=>ASSETS[p]||p;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const board=c=>'assets/board-'+c.id+'.png';
const current=()=>CONCEPTS.find(c=>c.id===state.concept);
let cropId=0;
function crop(path,rect,alt,fit='slice',dimensions=[1536,1024]){const[x,y,w,h]=rect;const clip='crop-'+(++cropId);return `<div class="crop" style="aspect-ratio:${w}/${h}"><svg viewBox="${x} ${y} ${w} ${h}" preserveAspectRatio="xMidYMid ${fit}" role="img" aria-label="${esc(alt)}"><defs><clipPath id="${clip}"><rect x="${x}" y="${y}" width="${w}" height="${h}"/></clipPath></defs><image clip-path="url(#${clip})" href="${asset(path)}" width="${dimensions[0]}" height="${dimensions[1]}"/></svg></div>`}
function rect(c,type){const x=c.cuts.x*1536,y1=c.cuts.y1*1024,y2=c.cuts.y2*1024;if(type==='product')return [0,0,x-7,1024];if(type==='caps')return [x+5,0,1536-x-5,y1-7];if(type==='macro')return [x+5,y1+5,1536-x-5,y2-y1-12];return [x+5,y2+5,1536-x-5,1024-y2-5]}
function imageButton(c,type,cls=''){return `<button class="image-button zoomable ${cls}" data-image="${board(c)}" data-title="${esc(c.name+' · '+({product:'нанесение бренда',caps:'крышки сверху',macro:'макро нанесения',mood:'мудборд'}[type]))}" aria-label="Увеличить: ${esc(c.name)}">${crop(board(c),rect(c,type),c.name+' — '+type,type==='product'?'meet':'slice')}</button>`}
function palette(c,labels=false){return `<div class="palette-row">${c.palette.map(color=>`<span style="background:${color}">${labels?'<b>'+color+'</b>':''}</span>`).join('')}</div>`}
function initCollection(){
 $('#conceptGrid').innerHTML=CONCEPTS.map(c=>`<button class="concept-card" data-concept="${c.id}" aria-pressed="${c.id===state.concept}"><div class="card-image"><span class="card-num">${c.num}</span>${crop(board(c),rect(c,'product'),c.name+' с брендом Первода')}</div><div class="card-title"><h3>${c.name}</h3><span>↗</span></div><p>${c.code}</p></button>`).join('');
 $('#conceptNav').innerHTML=CONCEPTS.map(c=>`<button data-concept="${c.id}" class="${c.id===state.concept?'active':''}" aria-label="${c.num} ${c.name}" aria-pressed="${c.id===state.concept}">${c.num}</button>`).join('');
 $$('.scene-nav').forEach(nav=>nav.innerHTML=CONCEPTS.map(c=>`<button data-concept="${c.id}" aria-pressed="false">${c.num} / ${c.name}</button>`).join(''));
 $('#productionChart').innerHTML=CONCEPTS.map(c=>`<div class="chart-row"><span class="chart-name">${c.name}</span><div class="chart-bars"><div class="score-track"><span class="score-fill" style="width:${c.production*10}%"><b>${c.production}</b></span><span class="sr-only">Сложность производства ${c.production} из 10</span></div><div class="score-track"><span class="score-fill implementation" style="width:${c.cost*10}%"><b>${c.cost}</b></span><span class="sr-only">Сложность внедрения ${c.cost} из 10</span></div></div></div>`).join('');
 const printSection=document.createElement('section');printSection.className='print-concepts';printSection.innerHTML=CONCEPTS.map(c=>`<article class="print-concept"><p class="eyebrow">Концепт ${c.num} / Первода</p><h2>${c.name} — ${c.subtitle}</h2><img src="${asset(board(c))}" alt="${c.name}: нанесение, крышки и мудборд"><p>${c.short}</p><p><b>Материалы.</b> ${c.material} <b>Крышка.</b> ${c.cap}</p><p><b>Производство ${c.production}/10.</b> ${c.risk}</p></article>`).join('');$('main').append(printSection);
}
function selectConcept(id,scroll=false){state.concept=id;const c=current();state.capFinish=c.finish;$$('[data-concept]').forEach(b=>{const selected=b.dataset.concept===id;b.setAttribute('aria-pressed',String(selected));b.classList.toggle('active',selected)});renderConcept();renderCap();renderScenes();if(scroll)$('#atelier').scrollIntoView({behavior:'smooth',block:'start'});try{localStorage.setItem('pervodaConcept',id)}catch{}}
function renderConcept(){const c=current();$('#activeNum').textContent=c.num;$('#activeName').textContent=c.name;$('#activeSubtitle').textContent=c.subtitle;$$('[data-tab]').forEach(b=>{const on=b.dataset.tab===state.tab;b.setAttribute('aria-selected',String(on));b.tabIndex=on?0:-1});const panel=$('#conceptPanel');panel.setAttribute('aria-label',c.name+' · '+state.tab);
 const product=`<div class="product-visual">${imageButton(c,'product')}<span class="product-label">${c.name} · новый рендер 0,5 л / pH 8.0</span></div>`;
 if(state.tab==='brand')panel.innerHTML=`<div class="concept-layout">${product}<div class="concept-info"><p class="eyebrow">Форма и нанесение</p><h3>${c.subtitle}</h3><p class="description">${c.detail}</p>${imageButton(c,'macro','detail-crop')}<div class="detail-list"><div><h4>Нанесение</h4><p>${c.print}</p></div><div><h4>Материал</h4><p>${c.material}</p></div></div>${palette(c)}<span class="status-tag">${c.recommend}</span></div></div>`;
 if(state.tab==='caps')panel.innerHTML=`<div class="concept-layout">${product}<div class="concept-info"><p class="eyebrow">Реалистичный вид сверху</p><h3>Три коротких сообщения.</h3>${imageButton(c,'caps','caps-photo')}<div class="cap-ideas"><div><h4>П</h4><p>Монограмма.<br>Бренд в одном знаке.</p></div><div><h4>pH 8.0</h4><p>Версия продукта.<br>Для 0,3 л — pH 12.</p></div><div><h4>20</h4><p>Числовой код.<br>Слово ppm — на корпусе.</p></div></div><div class="detail-list"><div><h4>Основная крышка</h4><p>${c.cap}</p></div><div><h4>Альтернатива</h4><p>${c.alt}</p></div></div><p class="back-caption">Варианты торца показаны отдельно. Размер, резьба, пищевой вкладыш и момент открывания согласуются с поставщиком укупорки.</p><a class="text-button" href="#capLab">Попробовать цвет и нанесение ↓</a></div></div>`;
 if(state.tab==='mood')panel.innerHTML=`<div class="mood-panel"><div><div class="mood-photo">${imageButton(c,'mood')}</div>${imageButton(c,'macro','detail-crop')}</div><div class="mood-details"><p class="eyebrow">Материалы / свет / настроение</p><h3>${c.code.split(' · ').join('.<br>')}.</h3><p class="note">Самостоятельная визуальная территория концепта «${c.name}».</p><ol class="mood-words">${c.moods.map((m,i)=>`<li><small>${i+1}</small>${m}</li>`).join('')}</ol><h4>Палитра концепта</h4>${palette(c,true)}<p class="back-caption" style="margin-top:52px">${c.material}</p></div></div>`;
 if(state.tab==='original')panel.innerHTML=`<div class="original-layout"><button class="image-button zoomable" data-image="assets/original-${c.id}.png" data-title="${c.name} · исходный борд заказчика"><img src="${asset('assets/original-'+c.id+'.png')}" alt="Исходный борд ${c.name}"></button><div class="original-note"><p class="eyebrow">Исходник / сохранён без изменения</p><h3>${c.name}</h3><p>${c.short}</p><p>Оригинальный борд объединяет проекции, предметный рендер, макро и полочную сцену. Новая брендовая версия доступна во вкладке «Нанесение».</p><p>Указанные в исходнике размеры, оценки и заявления относятся к ранней концепции. Актуальная линейка презентации: 0,3 л / pH 12; 0,5 и 1 л / pH 8.0; везде 20 ppm.</p><button class="button" data-tab-switch="brand">Перейти к бренду →</button></div></div>`;
 if(state.tab==='production')panel.innerHTML=`<div class="production-detail"><div class="metrics"><div class="metric"><strong>${c.production}<small>/10</small></strong><span>Сложность производства</span></div><div class="metric"><strong>${c.cost}<small>/10</small></strong><span>Относительная сложность внедрения</span></div><div class="metric"><strong class="recommend">${c.recommend}</strong><span>Дизайнерская оценка</span></div></div><div class="risk-box"><p class="eyebrow">Ключевой производственный вопрос</p><h3 style="margin-top:18px">${c.risk}</h3><p>${c.print}</p><p>Минимальная партия зависит от завода и программы производства. Опубликованные условия и различия между ними приведены ниже в разделе «Сравнение». Для этой формы и каждого объёма нужен отдельный ответ производителя.</p><p class="note">Оценки взяты из исходного борда и не подтверждены производителем. Сравниваем характер задач, а не обещаем стоимость или сроки.</p><a class="button" href="#compare">Сравнить все формы →</a></div></div>`;
}
function renderCap(){const s=SKUS[state.sku];const cap=$('#liveCap');cap.className='live-cap '+state.capFinish;const mark=$('#capMark');mark.className='cap-mark-'+state.capTechnique;const content={brand:'<div class="cap-main word">ПЕРВОДА</div>',monogram:'<div class="cap-main">П</div>',ph:'<div class="cap-main value">'+s.ph.replace('pH ','')+'</div><div class="cap-small">pH</div>',tds:'<div class="cap-main value">20</div><div class="cap-small">ppm</div>'};mark.innerHTML=content[state.capContent];
 for(const [group,key,field]of[['#capContent','capContent','content'],['#capFinish','capFinish','finish'],['#capTechnique','capTechnique','technique'],['#capSKU','sku','sku']])$$(group+' button').forEach(b=>{const on=b.dataset[field]===state[key];b.classList.toggle('selected',on);b.setAttribute('aria-pressed',on)});
 const explain={laser:'Лазер: тонкое контрастное нанесение. На лакированной поверхности — раскрытие металла; оттенок и контраст зависят от покрытия.',print:'Печать: наиболее управляемый контраст. Для графитового финиша предлагается светлая краска, для серебра и жемчуга — графитовая.',emboss:'Рельеф: тактильное тиснение торца. Требует отдельной оснастки; штрихи и глубину подбирают по пробным образцам.'};$('#capExplain').textContent=explain[state.capTechnique];
 $('#labelPh').textContent=s.ph;$('#labelVolume').textContent=s.volume;$('#hierarchySKU').textContent=s.ph+' · '+s.volume;$$('[data-line-sku]').forEach(b=>{const on=b.dataset.lineSku===state.sku;b.classList.toggle('selected',on);b.setAttribute('aria-pressed',on)});
}
const SCENE_RECTS={lineup:[0,0,2048,1020],shelf:[0,1028,1020,1020],table:[1028,1028,1020,1020]};
function sceneImage(c,type){const path='assets/scenes-'+c.id+'.png';const title=c.name+' · '+({lineup:'три объёма',shelf:'на полке · 0,5 л',table:'на столе · 1 л'}[type]);return `<button class="image-button zoomable scene-image" data-image="${path}" data-scene="${type}" data-title="${esc(title)}" aria-label="Увеличить: ${esc(title)}">${crop(path,SCENE_RECTS[type],title,'meet',[2048,2048])}</button>`}
function renderScenes(){const c=current();$$('[data-active-name]').forEach(n=>n.textContent=c.num+' / '+c.name);$('#lineupScene').innerHTML=sceneImage(c,'lineup');$('#shelfScene').innerHTML=sceneImage(c,'shelf');$('#tableScene').innerHTML=sceneImage(c,'table');}
function renderCompare(){$('#compareLine').innerHTML=CONCEPTS.map(c=>`<article class="compare-item"><div class="compare-img">${imageButton(c,'product')}</div><button class="compare-select" data-concept="${c.id}" aria-pressed="${c.id===state.concept}"><span>${c.num}</span><h3>${c.name}</h3><span>↗</span></button><p>${c.code}</p></article>`).join('')}
function openLightbox(path,title,scene){const img=$('#lightboxImage'),panel=$('#lightboxScene');img.hidden=!!scene;panel.hidden=!scene;if(scene){img.removeAttribute('src');panel.innerHTML=crop(path,SCENE_RECTS[scene],title,'meet',[2048,2048]);}else{panel.innerHTML='';img.src=asset(path);img.alt=title;img.classList.toggle('original',path.includes('original-'));}$('#lightboxTitle').textContent=title;$('#lightbox').showModal();}
document.addEventListener('click',e=>{const b=e.target.closest('button,a,[data-image]');if(!b)return;
 if(b.dataset.concept){selectConcept(b.dataset.concept,b.classList.contains('concept-card'));return}
 if(b.dataset.tab||b.dataset.tabSwitch){state.tab=b.dataset.tab||b.dataset.tabSwitch;renderConcept();return}
 if(b.classList.contains('zoomable')){openLightbox(b.dataset.image,b.dataset.title||'Первода',b.dataset.scene);return}
 for(const[field,key]of[['content','capContent'],['finish','capFinish'],['technique','capTechnique'],['sku','sku'],['lineSku','sku']])if(b.dataset[field]){state[key]=b.dataset[field];renderCap();return}
});
$('.tabbar').addEventListener('keydown',e=>{if(!['ArrowRight','ArrowLeft','Home','End'].includes(e.key))return;e.preventDefault();const tabs=$$('[data-tab]'),index=tabs.findIndex(t=>t.dataset.tab===state.tab);let n=e.key==='Home'?0:e.key==='End'?tabs.length-1:(index+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;state.tab=tabs[n].dataset.tab;renderConcept();tabs[n].focus()});
$('#nextConcept').addEventListener('click',()=>{const i=CONCEPTS.findIndex(c=>c.id===state.concept);selectConcept(CONCEPTS[(i+1)%CONCEPTS.length].id)});

$('#closeLightbox').addEventListener('click',()=>$('#lightbox').close());$('#lightbox').addEventListener('click',e=>{if(e.target===$('#lightbox'))$('#lightbox').close()});
$('#printBtn').addEventListener('click',()=>window.print());
initCollection();try{const saved=localStorage.getItem('pervodaConcept');if(CONCEPTS.some(c=>c.id===saved))state.concept=saved}catch{}renderCompare();selectConcept(state.concept);
